name: model
description: The model.
version: 0.0.2

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  mockito: ^2.0.0
  quiver: any

transformers:
- angular

- test/pub_serve:
    $include: test/**_test{.*,}.dart