name: web_app
description: The AngularDart version of https://github.com/Shinpeim/NekogataDrumSequencer
version: 0.0.2
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular: ^4.0.0
  angular_components: ^0.7.0
  model:
    path: ../model
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  
web:
  compiler:
    debug: dartdevc
  
transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
